### ISSUE TITLE
Dedot and other stamps

### ISSUE THREAD

**Issue by CyberTaoFlow** [J-Gras/add-json#1]
Greetings!

I just wanted to pass some options along i found useful when using bro json output with elasticsearch.

Later versions (2.x) dont allow dots in keys anymore, so I had  to drop this into my local.bro

#below needed to dedot json  for ES
redef Log::default_scope_sep="_";

Optionally you could add this timestamp to your package (commented out or whatever)

redef LogAscii::json_timestamps = JSON::TS_ISO8601;

**Comment by J-Gras** [comment]
Hi @CyberTaoFlow,
thanks for your feedback!

> Later versions (2.x) dont allow dots in keys anymore, so I had to drop this into my local.bro
> #below needed to dedot json for ES
> redef Log::default_scope_sep="_";

Good point! I have added a `Log::scope_sep_json` option so that you can configure an alternative scope separator for JSON only. Once I update the README, I will add a hint.

> Optionally you could add this timestamp to your package (commented out or whatever)
> redef LogAscii::json_timestamps = JSON::TS_ISO8601;

There is already an option `timestamps_json` that can be used to configure timestamps. So you might use `redef Log::timestamps_json = JSON::TS_ISO8601;` to change the timestamp format for the logs generated by this script. The idea is that users can customize these things in their `local.bro` file.

I hope that helps!
